name: Build and Push Docker image time backend

on:
  push:
    branches: [ "master" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rafo1127/time-backend
      
    - name: Push Docker image to Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/time-backend:latest
